### PR TITLE
Added solid-square chain svgs

### PR DESCRIPTION
**Pull request by blurrytweaks**
All chains solid, square svgs ;)

### CODE REVIEW

**Review by ecdsafu — CHANGES_REQUESTED** [review]
Looks great, nice work. The only one I'd change is the Cosmos hub icon - the circle icon could be a bit smaller so it doesn't touch the edges? Interested in your thoughts

**Comment by blurrytweaks** [comment]
You were right! Done ;)

**Review by ecdsafu — CHANGES_REQUESTED** [review]
Ah, dYdX has the wrong name. Can you change to dydx.svg?
Polygon could we do purple background, white logo?
And could we get on a black background Scroll, Persistence, Mars
Kava can we get a white K and red background?

**Comment by blurrytweaks** [comment]
Hey! fast as flash, if u have any other possible improvement just ask for it! kind regards fr

**Review by ecdsafu — APPROVED** [review]
lgtm!

**Pull request merged**
